pipeline {
    // agent {
    //     docker {
    //         image 'maven:3.9.0'
    //         args '-v /root/.m2:/root/.m2'
    //     }
    // }
    agent any

    environment {
        passphraseVariable = credentials('ssh-pass')
        usernameVariable = credentials('username')
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            withCredentials([sshUserPrivateKey(credentialsId: 'web', keyFileVariable: 'identity', passphraseVariable: "$passphraseVariable" , usernameVariable: "$usernameVariable" )]) {

                    writeFile file: 'abc.sh', text: 'ls'
            }
        }
        // stage('Deliver') {
        //     steps {
        //         sh './Jenkins/scripts/deliver.sh'
        //     }
        // }
    }
}