pipeline {
    // agent {
    //     docker {
    //         image 'maven:3.9.0'
    //         args '-v /root/.m2:/root/.m2'
    //     }
    // }
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'echo $M2_HOME'
                sh 'echo $JAVA_HOME'
                sh 'export MAVEN_HOME=/home/vagrant/maven/apache-maven-3.9.1'
                sh 'export PATH=$PATH:$MAVEN_HOME/bin'
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}